@extends('layouts.app')
@section('title', 'Administration')
@section('heading', 'Administration')
@section('content')
<div class="mb-6"><p class="eyebrow">Configuration</p><h2 class="mt-2 text-3xl font-semibold">Administration du système</h2><p class="mt-2 text-slate-500">Utilisateurs, organisations et ressources du réseau.</p></div>
<div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">@foreach([['Organisations',$stats['organizations']],['Sites',$stats['sites']],['Caméras',$stats['cameras']],['Utilisateurs',$stats['users']]] as [$label,$value])<article class="panel p-5"><p class="text-sm text-slate-500">{{ $label }}</p><p class="mt-2 text-3xl font-semibold">{{ $value }}</p></article>@endforeach</div>
<section class="panel mt-6 flex flex-col justify-between gap-4 p-5 sm:flex-row sm:items-center"><div><p class="eyebrow">Infrastructure</p><h3 class="mt-1 font-semibold">Sites de rattachement</h3><p class="mt-1 text-sm text-slate-500">Gérez les emplacements auxquels les caméras sont associées.</p></div><a href="{{ route('sites.index') }}" class="btn-primary">Gérer les sites</a></section>
<section class="panel mt-6 overflow-hidden"><div class="flex items-center justify-between border-b border-slate-100 p-5"><div><p class="eyebrow">Accès</p><h3 class="mt-1 font-semibold">Utilisateurs</h3></div><button class="btn-primary" disabled title="Disponible dans la prochaine itération">Ajouter un utilisateur</button></div><div class="overflow-x-auto"><table class="w-full min-w-3xl text-left text-sm"><thead class="bg-slate-50 text-xs tracking-wide text-slate-500 uppercase"><tr><th class="px-5 py-3">Utilisateur</th><th class="px-5 py-3">Organisation</th><th class="px-5 py-3">Rôles</th><th class="px-5 py-3">Dernière connexion</th><th class="px-5 py-3">État</th></tr></thead><tbody class="divide-y divide-slate-100">@foreach($users as $user)<tr><td class="px-5 py-4"><p class="font-semibold">{{ $user->name }}</p><p class="text-xs text-slate-500">{{ $user->email }}</p></td><td class="px-5 py-4">{{ $user->organization?->name ?? 'Global' }}</td><td class="px-5 py-4"><div class="flex flex-wrap gap-1">@forelse($user->roles as $role)<span class="rounded-full bg-slate-100 px-2 py-1 text-xs font-semibold">{{ $role->name }}</span>@empty<span class="text-slate-400">Aucun</span>@endforelse</div></td><td class="px-5 py-4 text-slate-500">{{ $user->last_login_at?->diffForHumans() ?? 'Jamais' }}</td><td class="px-5 py-4"><span class="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-semibold text-emerald-700">{{ str($user->status)->headline() }}</span></td></tr>@endforeach</tbody></table></div></section><div class="mt-6">{{ $users->links() }}</div>
@endsection
