@extends('layouts.app')
@section('title', 'Ajouter une caméra')
@section('heading', 'Nouvelle caméra')
@section('content')
<div class="mx-auto max-w-5xl">
    <div class="mb-6"><a href="{{ route('cameras.index') }}" class="text-sm font-semibold text-lynx-700">← Retour aux caméras</a><p class="eyebrow mt-5">Configuration du réseau</p><h2 class="mt-2 text-3xl font-semibold">Ajouter une caméra</h2><p class="mt-2 text-slate-500">Renseignez la connexion, la position et les capacités d’analyse.</p></div>
    @if($sites->isEmpty())<div class="mb-6 flex flex-col justify-between gap-3 rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-800 sm:flex-row sm:items-center"><span>Aucun site actif n’est disponible. Créez d’abord un site.</span><a href="{{ route('sites.index') }}" class="font-semibold underline">Ajouter un site →</a></div>@endif
    <form method="POST" action="{{ route('cameras.store') }}" class="space-y-6">@csrf
        <section class="panel p-5 sm:p-7"><div class="mb-6"><p class="eyebrow">01 · Identification</p><h3 class="mt-1 text-lg font-semibold">Informations générales</h3></div><div class="grid gap-5 md:grid-cols-2">
            <label class="block"><span class="mb-2 block text-sm font-medium">Nom de la caméra *</span><input name="name" value="{{ old('name') }}" required maxlength="150" placeholder="Caméra Carrefour Centre" class="w-full rounded-xl border border-slate-300 px-4 py-3 focus:border-lynx-500 focus:ring-3 focus:ring-lynx-100 focus:outline-none">@error('name')<span class="mt-1 block text-sm text-red-600">{{ $message }}</span>@enderror</label>
            <label class="block"><span class="mb-2 block text-sm font-medium">Code unique *</span><input name="code" value="{{ old('code') }}" required maxlength="50" placeholder="CAM-001" class="w-full rounded-xl border border-slate-300 px-4 py-3 uppercase focus:border-lynx-500 focus:ring-3 focus:ring-lynx-100 focus:outline-none">@error('code')<span class="mt-1 block text-sm text-red-600">{{ $message }}</span>@enderror</label>
            <label class="block md:col-span-2"><span class="mb-2 block text-sm font-medium">Site de rattachement *</span><select name="site_id" required class="w-full rounded-xl border border-slate-300 bg-white px-4 py-3 focus:border-lynx-500 focus:ring-3 focus:ring-lynx-100 focus:outline-none"><option value="">Sélectionner un site</option>@foreach($sites as $site)<option value="{{ $site->id }}" @selected(old('site_id')===$site->id)>{{ $site->name }}{{ $site->address ? ' — '.$site->address : '' }}</option>@endforeach</select>@error('site_id')<span class="mt-1 block text-sm text-red-600">{{ $message }}</span>@enderror</label>
        </div></section>
        <section class="panel p-5 sm:p-7"><div class="mb-6"><p class="eyebrow">02 · Connexion</p><h3 class="mt-1 text-lg font-semibold">Flux vidéo sécurisé</h3></div><div class="grid gap-5 md:grid-cols-[180px_1fr]">
            <label class="block"><span class="mb-2 block text-sm font-medium">Protocole *</span><select name="protocol" class="w-full rounded-xl border border-slate-300 bg-white px-4 py-3"><option value="rtsp" @selected(old('protocol','rtsp')==='rtsp')>RTSP</option><option value="rtsps" @selected(old('protocol')==='rtsps')>RTSPS</option><option value="http" @selected(old('protocol')==='http')>HTTP</option><option value="https" @selected(old('protocol')==='https')>HTTPS</option></select></label>
            <label class="block"><span class="mb-2 block text-sm font-medium">URL du flux *</span><input name="stream_url" value="{{ old('stream_url') }}" required type="password" autocomplete="off" placeholder="rtsp://utilisateur:motdepasse@adresse/flux" class="w-full rounded-xl border border-slate-300 px-4 py-3 font-mono text-sm focus:border-lynx-500 focus:ring-3 focus:ring-lynx-100 focus:outline-none"><span class="mt-1 block text-xs text-slate-500">L’adresse et ses identifiants seront chiffrés dans la base.</span>@error('stream_url')<span class="mt-1 block text-sm text-red-600">{{ $message }}</span>@enderror</label>
        </div></section>
        <section class="panel p-5 sm:p-7"><div class="mb-6"><p class="eyebrow">03 · Position</p><h3 class="mt-1 text-lg font-semibold">Géolocalisation et orientation</h3></div><div class="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">
            <label><span class="mb-2 block text-sm font-medium">Latitude</span><input name="latitude" type="number" step="0.0000001" min="-90" max="90" value="{{ old('latitude') }}" placeholder="-11.6647" class="w-full rounded-xl border border-slate-300 px-4 py-3">@error('latitude')<span class="mt-1 block text-sm text-red-600">{{ $message }}</span>@enderror</label>
            <label><span class="mb-2 block text-sm font-medium">Longitude</span><input name="longitude" type="number" step="0.0000001" min="-180" max="180" value="{{ old('longitude') }}" placeholder="27.4794" class="w-full rounded-xl border border-slate-300 px-4 py-3">@error('longitude')<span class="mt-1 block text-sm text-red-600">{{ $message }}</span>@enderror</label>
            <label><span class="mb-2 block text-sm font-medium">Orientation (degrés)</span><input name="direction_degrees" type="number" step="0.01" min="0" max="359.99" value="{{ old('direction_degrees') }}" placeholder="90" class="w-full rounded-xl border border-slate-300 px-4 py-3">@error('direction_degrees')<span class="mt-1 block text-sm text-red-600">{{ $message }}</span>@enderror</label>
        </div></section>
        <section class="panel p-5 sm:p-7"><div class="mb-6"><p class="eyebrow">04 · Exploitation</p><h3 class="mt-1 text-lg font-semibold">État et capacités IA</h3></div><div class="grid gap-6 lg:grid-cols-[220px_1fr]"><label><span class="mb-2 block text-sm font-medium">État initial *</span><select name="status" class="w-full rounded-xl border border-slate-300 bg-white px-4 py-3"><option value="offline">Hors ligne</option><option value="online" @selected(old('status')==='online')>En ligne</option><option value="maintenance" @selected(old('status')==='maintenance')>Maintenance</option></select></label><fieldset><legend class="mb-3 text-sm font-medium">Analyses disponibles</legend><div class="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">@foreach(['person'=>'Personnes','vehicle'=>'Véhicules','plate'=>'Plaques','crowd'=>'Attroupements','intrusion'=>'Intrusions'] as $value=>$label)<label class="flex items-center gap-3 rounded-xl border border-slate-200 p-3 text-sm"><input type="checkbox" name="capabilities[]" value="{{ $value }}" @checked(in_array($value,old('capabilities',[]))) class="rounded border-slate-300 text-lynx-600">{{ $label }}</label>@endforeach</div>@error('capabilities.*')<span class="mt-1 block text-sm text-red-600">{{ $message }}</span>@enderror</fieldset></div></section>
        <div class="flex flex-col-reverse justify-end gap-3 sm:flex-row"><a href="{{ route('cameras.index') }}" class="btn-secondary">Annuler</a><button class="btn-primary" @disabled($sites->isEmpty())>Enregistrer la caméra</button></div>
    </form>
</div>
@endsection
