@extends('layouts.app')
@section('title', 'Sites de rattachement')
@section('heading', 'Sites de rattachement')
@section('content')
<div class="mb-6"><a href="{{ route('admin.index') }}" class="text-sm font-semibold text-lynx-700">← Administration</a><p class="eyebrow mt-5">Infrastructure</p><h2 class="mt-2 text-3xl font-semibold">Gérer les sites</h2><p class="mt-2 text-slate-500">Un site regroupe les caméras installées au même emplacement opérationnel.</p></div>
<div class="grid items-start gap-6 xl:grid-cols-[400px_1fr]">
    <section class="panel p-5 sm:p-6 xl:sticky xl:top-28"><p class="eyebrow">Nouveau site</p><h3 class="mt-1 text-lg font-semibold">Ajouter un emplacement</h3><form method="POST" action="{{ route('sites.store') }}" class="mt-6 space-y-5">@csrf
        <label class="block"><span class="mb-2 block text-sm font-medium">Nom du site *</span><input name="name" value="{{ old('name') }}" required maxlength="150" placeholder="Carrefour Centre-ville" class="w-full rounded-xl border border-slate-300 px-4 py-3 focus:border-lynx-500 focus:ring-3 focus:ring-lynx-100 focus:outline-none">@error('name')<span class="mt-1 block text-sm text-red-600">{{ $message }}</span>@enderror</label>
        <label class="block"><span class="mb-2 block text-sm font-medium">Adresse</span><textarea name="address" rows="3" maxlength="1000" placeholder="Avenue, commune, ville" class="w-full rounded-xl border border-slate-300 px-4 py-3 focus:border-lynx-500 focus:ring-3 focus:ring-lynx-100 focus:outline-none">{{ old('address') }}</textarea>@error('address')<span class="mt-1 block text-sm text-red-600">{{ $message }}</span>@enderror</label>
        <div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-1 2xl:grid-cols-2"><label><span class="mb-2 block text-sm font-medium">Latitude</span><input name="latitude" type="number" step="0.0000001" min="-90" max="90" value="{{ old('latitude') }}" placeholder="-11.6647" class="w-full rounded-xl border border-slate-300 px-4 py-3">@error('latitude')<span class="mt-1 block text-sm text-red-600">{{ $message }}</span>@enderror</label><label><span class="mb-2 block text-sm font-medium">Longitude</span><input name="longitude" type="number" step="0.0000001" min="-180" max="180" value="{{ old('longitude') }}" placeholder="27.4794" class="w-full rounded-xl border border-slate-300 px-4 py-3">@error('longitude')<span class="mt-1 block text-sm text-red-600">{{ $message }}</span>@enderror</label></div>
        <label class="block"><span class="mb-2 block text-sm font-medium">Fuseau horaire *</span><select name="timezone" class="w-full rounded-xl border border-slate-300 bg-white px-4 py-3"><option value="Africa/Lubumbashi" @selected(old('timezone','Africa/Lubumbashi')==='Africa/Lubumbashi')>Africa/Lubumbashi</option><option value="Africa/Kinshasa" @selected(old('timezone')==='Africa/Kinshasa')>Africa/Kinshasa</option><option value="UTC" @selected(old('timezone')==='UTC')>UTC</option></select>@error('timezone')<span class="mt-1 block text-sm text-red-600">{{ $message }}</span>@enderror</label>
        <label class="flex items-center gap-3 rounded-xl bg-slate-50 p-4 text-sm"><input type="checkbox" name="active" value="1" @checked(old('active',true)) class="rounded border-slate-300 text-lynx-600"><span><strong class="block">Site actif</strong><span class="text-slate-500">Disponible dans les formulaires caméra.</span></span></label>
        <button class="btn-primary w-full">Enregistrer le site</button>
    </form></section>
    <section class="panel overflow-hidden"><div class="flex items-center justify-between border-b border-slate-100 p-5"><div><p class="eyebrow">Répertoire</p><h3 class="mt-1 font-semibold">{{ $sites->total() }} sites enregistrés</h3></div></div><div class="divide-y divide-slate-100">@forelse($sites as $site)<article class="flex flex-col justify-between gap-4 p-5 sm:flex-row sm:items-center"><div class="flex min-w-0 gap-4"><div class="grid size-11 shrink-0 place-items-center rounded-xl bg-lynx-50 text-lynx-700"><svg class="size-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M20 10c0 5-8 11-8 11S4 15 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/></svg></div><div class="min-w-0"><div class="flex flex-wrap items-center gap-2"><h4 class="font-semibold">{{ $site->name }}</h4><span class="rounded-full px-2 py-0.5 text-xs font-semibold {{ $site->active ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-100 text-slate-500' }}">{{ $site->active ? 'Actif' : 'Inactif' }}</span></div><p class="mt-1 truncate text-sm text-slate-500">{{ $site->address ?: 'Adresse non renseignée' }}</p><p class="mt-1 text-xs text-slate-400">{{ $site->latitude ?? '—' }}, {{ $site->longitude ?? '—' }} · {{ $site->timezone }}</p></div></div><div class="shrink-0 rounded-xl bg-slate-50 px-4 py-2 text-center"><p class="text-xl font-semibold">{{ $site->cameras_count }}</p><p class="text-xs text-slate-500">caméra{{ $site->cameras_count > 1 ? 's' : '' }}</p></div></article>@empty<div class="p-12 text-center"><p class="font-semibold">Aucun site enregistré</p><p class="mt-1 text-sm text-slate-500">Utilisez le formulaire pour créer le premier emplacement.</p></div>@endforelse</div>@if($sites->hasPages())<div class="border-t border-slate-100 p-5">{{ $sites->links() }}</div>@endif</section>
</div>
@endsection
